---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: "Include file creation"
      ansible.builtin.include_role:
        name: "file_creation"