---
- name: Verify for file_creation role
  hosts: all
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
    - name: Create a test file
      copy:
        content: "This is a test file."
        dest: "{{ file_path }}"