---
- name: Create a directory
  file:
    path: "{{ directory_path }}"
    state: directory

- name: Create a file inside the directory
  copy:
    content: "This is the content of the file."
    dest: "{{ file_path }}"